### ISSUE TITLE
ITMS-90430: invalid Swift Support - The file libsrt.1.4.dylib does't have a signing ID. Sign the file, rebuild your app using the current public(GM) version of Xcode and resubmit it.

### ISSUE THREAD

**Issue by wallecechen** [hwangsaeul/libsrt#2]
I met the ITMS-90430/90426: invalid Swift support w/ no libsrt.1.4.dylib signing ID when uploading to App store.
Researching the other suggestions from internet, but no solution at all even I did :
1. "Always embedded swift support enable" -> [YES] @ build option of Xcode
2. Auto-create "SwiftSupport" by "Package_ipa.sh"
3. Embedded w/ signed at "General" option of XCode for libsrt.1.4.dylib ==> it is working fine to execute from the iphone/ipad via  XCode.

Anyone can help how to fix the signing ID problem for libsrt.1.4.dylib? Or others solution.
thanks

**Comment by justinjoy** [comment]
@wallecechen Thank you for the reporting.
However, this repository is forked for Linux-based application development, and issues on other platforms are not considered here.

If you don't mind, could you post your report upstream again? 
This is the upstream link; https://github.com/Haivision/srt

**Comment by wallecechen** [comment]
@justinjoy , understood. it already moved to the upstream link.
